import type { Metadata } from "next";
import { Inter, Krona_One, Quicksand } from "next/font/google";
import "./globals.css";

const krona = Krona_One({
  subsets: ["latin"],
  weight: ["400"],

  variable: "--font-krona",
});

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`  ${krona.variable} ${quicksand.variable} font-krona`}>
        {children}
      </body>
    </html>
  );
}
